import { Team } from './team.class';

export const teams: Team[] = [
    new Team(0, 'Anaheim Ducks',  24, 'url', 'forumId'),
    new Team(1, 'Arizona Coyote',  53, 'url', 'forumId'),
    new Team(2, 'Boston Bruins',  6, 'url', 'forumId'),
    new Team(3, 'Buffalo Sabres',  7, 'url', 'forumId'),
    new Team(4, 'Calgary Flames',  20, 'url', '5e77b57de3d58bd5c347a3e6'),
    new Team(5, 'Carolina Hurricanes',  12, 'url', 'forumId'),
    new Team(6, 'Chicago Blackhawks',  16, 'url', 'forumId'),
    new Team(7, 'Colorado Avalanche',  21, 'url', 'forumId'),
    new Team(8, 'Columbus Blue Jackets',  29, 'url', 'forumId'),
    new Team(9, 'Dallas Stars',  25, 'url', 'forumId'),
    new Team(10, 'Detroit Red Wings',  17, 'url', 'forumId'),
    new Team(11, 'Edmonton Oilers',  22, 'url', 'forumId'),
    new Team(12, 'Florida Panthers',  13, 'url', 'forumId'),
    new Team(13, 'Los Angeles Kings',  26, 'url', 'forumId'),
    new Team(14, 'Minnesota Wild',  30, 'url', 'forumId'),
    new Team(15, 'Montreal Canadiens',  8, 'url', 'forumId'),
    new Team(16, 'Nashville Predators',  18, 'url', 'forumId'),
    new Team(17, 'New Jersey Devils',  1, 'url', 'forumId'),
    new Team(18, 'New York Islanders',  2, 'url', 'forumId'),
    new Team(19, 'New York Rangers',  3, 'url', 'forumId'),
    new Team(20, 'Ottawa Senators',  9, 'url', 'forumId'),
    new Team(21, 'Philadelphia Flyers',  4, 'url', 'forumId'),
    new Team(22, 'Pittsburgh Penguins',  5, 'url', 'forumId'),
    new Team(23, 'San Jose Sharks',  28, 'url', 'forumId'),
    new Team(24, 'St. Louis Blues',  19, 'url', 'forumId'),
    new Team(25, 'Tampa Bay Lightning',  14, 'url', 'forumId'),
    new Team(26, 'Toronto Maple Leafs',  10, 'url', 'forumId'),
    new Team(27, 'Vancouver Canucks',  23, 'url', 'forumId'),
    new Team(28, 'Vegas Golden Knights',  54, 'url', 'forumId'),
    new Team(29, 'Washington Capitals',  15, 'url', 'forumId'),
    new Team(30, 'Winnipeg Jets',  52, 'url', 'forumId')
];

// export const teams: Map<number, string> = new Map([
//     [1, 'New Jersey Devils'],
//     [2, 'New York Islanders'],
//     [3, 'New York Rangers'],
//     [4, 'Philadelphia Flyers'],
//     [5, 'Pittsburgh Penguins'],
//     [6, 'Boston Bruins'],
//     [7, 'Buffalo Sabres'],
//     [8, 'Montreal Canadiens'],
//     [9, 'Ottawa Senators'],
//     [10, 'Toronto Maple Leafs'],
//     [12, 'Carolina Hurricanes'],
//     [13, 'Florida Panthers'],
//     [14, 'Tampa Bay Lightning'],
//     [15, 'Washington Capitals'],
//     [16, 'Chicago Blackhawks'],
//     [17, 'Detroit Red Wings'],
//     [18, 'Nashville Predators'],
//     [19, 'St. Louis Blues'],
//     [20, 'Calgary Flames'],
//     [21, 'Colorado Avalanche'],
//     [22, 'Edmonton Oilers'],
//     [23, 'Vancouver Canucks'],
//     [24, 'Anaheim Ducks'],
//     [25, 'Dallas Stars'],
//     [26, 'Los Angeles Kings'],
//     [28, 'San Jose Sharks'],
//     [29, 'Columbus Blue Jackets'],
//     [30, 'Minnesota Wild'],
//     [52, 'Winnipeg Jets'],
//     [52, 'Arizona Coyote'],
//     [54, 'Vegas Golden Knights']]);



    // export const teams: Map<number, string> = new Map([
    //     [1, 'New Jersey Devils'],
    //     [2, 'New York Islanders'],
    //     [3, 'New York Rangers'],
    //     [4, 'Philadelphia Flyers'],
    //     [5, 'Pittsburgh Penguins'],
    //     [6, 'Boston Bruins'],
    //     [7, 'Buffalo Sabres'],
    //     [8, 'Montreal Canadiens'],
    //     [9, 'Ottawa Senators'],
    //     [10, 'Toronto Maple Leafs'],
    //     [12, 'Carolina Hurricanes'],
    //     [13, 'Florida Panthers'],
    //     [14, 'Tampa Bay Lightning'],
    //     [15, 'Washington Capitals'],
    //     [16, 'Chicago Blackhawks'],
    //     [17, 'Detroit Red Wings'],
    //     [18, 'Nashville Predators'],
    //     [19, 'St. Louis Blues'],
    //     [20, 'Calgary Flames'],
    //     [21, 'Colorado Avalanche'],
    //     [22, 'Edmonton Oilers'],
    //     [23, 'Vancouver Canucks'],
    //     [24, 'Anaheim Ducks'],
    //     [25, 'Dallas Stars'],
    //     [26, 'Los Angeles Kings'],
    //     [28, 'San Jose Sharks'],
    //     [29, 'Columbus Blue Jackets'],
    //     [30, 'Minnesota Wild'],
    //     [52, 'Winnipeg Jets'],
    //     [52, 'Arizona Coyote'],
    //     [54, 'Vegas Golden Knights']]);
