import { Team } from './team.class';

export const teams: Team[] = [
    new Team(0, 'Anaheim Ducks',  24, '24_Anaheim_Ducks.png', 'forumId'),
    new Team(1, 'Arizona Coyote',  53, '53_Arizona_Coyote.png', 'forumId'),
    new Team(2, 'Boston Bruins',  6, '6_Boston_Bruins.png', 'forumId'),
    new Team(3, 'Buffalo Sabres',  7, '7_Buffalo_Sabres.png', 'forumId'),
    new Team(4, 'Calgary Flames',  20, '20_Calgary_Flames.png', '5e77b57de3d58bd5c347a3e6'),
    new Team(5, 'Carolina Hurricanes',  12, '12_Carolina_Hurricanes.png', 'forumId'),
    new Team(6, 'Chicago Blackhawks',  16, '16_Chicago_Blackhawks.png', 'forumId'),
    new Team(7, 'Colorado Avalanche',  21, '21_Colorado_Avalanche.png', 'forumId'),
    new Team(8, 'Columbus Blue Jackets',  29, '29_Columbus_Blue_Jackets.png', 'forumId'),
    new Team(9, 'Dallas Stars',  25, '25_Dallas_Stars.png', 'forumId'),
    new Team(10, 'Detroit Red Wings',  17, '17_Detroit_Red_Wings.png', 'forumId'),
    new Team(11, 'Edmonton Oilers',  22, '22_Edmonton_Oilers.png', 'forumId'),
    new Team(12, 'Florida Panthers',  13, '13_Florida_Panthers.png', 'forumId'),
    new Team(13, 'Los Angeles Kings',  26, '26_Los_Angeles_Kings.png', 'forumId'),
    new Team(14, 'Minnesota Wild',  30, '30_Minnesota_Wild.png', 'forumId'),
    new Team(15, 'Montreal Canadiens',  8, '8_Montreal_Canadiens.png', 'forumId'),
    new Team(16, 'Nashville Predators',  18, '18_Nashville_Predators.png', 'forumId'),
    new Team(17, 'New Jersey Devils',  1, '1_New_Jersey_Devils.png', 'forumId'),
    new Team(18, 'New York Islanders',  2, '2_New_York_Islanders.png', 'forumId'),
    new Team(19, 'New York Rangers',  3, '3_New_York_Rangers.png', 'forumId'),
    new Team(20, 'Ottawa Senators',  9, '9_Ottawa_Senators.png', 'forumId'),
    new Team(21, 'Philadelphia Flyers',  4, '4_Philadelphia_Flyers.png', 'forumId'),
    new Team(22, 'Pittsburgh Penguins',  5, '5_Pittsburgh_Penguins.png', 'forumId'),
    new Team(23, 'San Jose Sharks',  28, '28_San_Jose_Sharks.png', 'forumId'),
    new Team(24, 'St. Louis Blues',  19, '19_St._Louis_Blues.png', 'forumId'),
    new Team(25, 'Tampa Bay Lightning',  14, '14_Tampa_Bay_Lightning.png', 'forumId'),
    new Team(26, 'Toronto Maple Leafs',  10, '10_Toronto_Maple_Leafs.png', 'forumId'),
    new Team(27, 'Vancouver Canucks',  23, '23_Vancouver_Canucks.png', 'forumId'),
    new Team(28, 'Vegas Golden Knights',  54, '54_Vegas_Golden_Knights.png', 'forumId'),
    new Team(29, 'Washington Capitals',  15, '15_Washington_Capitals.png', 'forumId'),
    new Team(30, 'Winnipeg Jets',  52, '52_Winnipeg_Jets.png', 'forumId')
];

// export const teams: Map<number, string> = new Map([
//     [1, 'New Jersey Devils'],
//     [2, 'New York Islanders'],
//     [3, 'New York Rangers'],
//     [4, 'Philadelphia Flyers'],
//     [5, 'Pittsburgh Penguins'],
//     [6, 'Boston Bruins'],
//     [7, 'Buffalo Sabres'],
//     [8, 'Montreal Canadiens'],
//     [9, 'Ottawa Senators'],
//     [10, 'Toronto Maple Leafs'],
//     [12, 'Carolina Hurricanes'],
//     [13, 'Florida Panthers'],
//     [14, 'Tampa Bay Lightning'],
//     [15, 'Washington Capitals'],
//     [16, 'Chicago Blackhawks'],
//     [17, 'Detroit Red Wings'],
//     [18, 'Nashville Predators'],
//     [19, 'St. Louis Blues'],
//     [20, 'Calgary Flames'],
//     [21, 'Colorado Avalanche'],
//     [22, 'Edmonton Oilers'],
//     [23, 'Vancouver Canucks'],
//     [24, 'Anaheim Ducks'],
//     [25, 'Dallas Stars'],
//     [26, 'Los Angeles Kings'],
//     [28, 'San Jose Sharks'],
//     [29, 'Columbus Blue Jackets'],
//     [30, 'Minnesota Wild'],
//     [52, 'Winnipeg Jets'],
//     [52, 'Arizona Coyote'],
//     [54, 'Vegas Golden Knights']]);



    // export const teams: Map<number, string> = new Map([
    //     [1, 'New Jersey Devils'],
    //     [2, 'New York Islanders'],
    //     [3, 'New York Rangers'],
    //     [4, 'Philadelphia Flyers'],
    //     [5, 'Pittsburgh Penguins'],
    //     [6, 'Boston Bruins'],
    //     [7, 'Buffalo Sabres'],
    //     [8, 'Montreal Canadiens'],
    //     [9, 'Ottawa Senators'],
    //     [10, 'Toronto Maple Leafs'],
    //     [12, 'Carolina Hurricanes'],
    //     [13, 'Florida Panthers'],
    //     [14, 'Tampa Bay Lightning'],
    //     [15, 'Washington Capitals'],
    //     [16, 'Chicago Blackhawks'],
    //     [17, 'Detroit Red Wings'],
    //     [18, 'Nashville Predators'],
    //     [19, 'St. Louis Blues'],
    //     [20, 'Calgary Flames'],
    //     [21, 'Colorado Avalanche'],
    //     [22, 'Edmonton Oilers'],
    //     [23, 'Vancouver Canucks'],
    //     [24, 'Anaheim Ducks'],
    //     [25, 'Dallas Stars'],
    //     [26, 'Los Angeles Kings'],
    //     [28, 'San Jose Sharks'],
    //     [29, 'Columbus Blue Jackets'],
    //     [30, 'Minnesota Wild'],
    //     [52, 'Winnipeg Jets'],
    //     [52, 'Arizona Coyote'],
    //     [54, 'Vegas Golden Knights']]);
